spring:
  application:
    name: win-marketplace
  
  datasource:
    url: jdbc:postgresql://postgres:5432/win_marketplace
    username: postgres
    password: postgres123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
  
  jpa:
    hibernate:
      ddl-auto: none  # ✅ Desabilita validação estrita - deixa Flyway gerenciar schema
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: America/Sao_Paulo
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

server:
  port: 8080
  compression:
    enabled: true
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    root: INFO
    com.win.marketplace: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG