spring:
  application:
    name: win-marketplace
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/win_marketplace}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres123}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 300000
      max-lifetime: 1200000
  
  jpa:
    hibernate:
      ddl-auto: update  # ✅ Cria/atualiza tabelas automaticamente
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: America/Sao_Paulo
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
  sql:
    init:
      mode: always  # ✅ Executa scripts SQL na inicialização
      continue-on-error: false
  
  # Configurações de Email (JavaMailSender)
  # Suporta Gmail e SendGrid através de variáveis de ambiente
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
        from: ${MAIL_FROM:noreply@winmarketplace.com}  # Email remetente
    test-connection: false  # Não falhar se email não configurado
    
  # SendGrid Configuration (alternativa ao Gmail)
  # Para usar SendGrid, defina:
  #   MAIL_HOST=smtp.sendgrid.net
  #   MAIL_PORT=587
  #   MAIL_USERNAME=apikey
  #   MAIL_PASSWORD=SG.sua-api-key-aqui
  #   MAIL_FROM=seu-email-verificado@gmail.com

server:
  port: 8080

# Configurações da aplicação
app:
  frontend:
    url: ${FRONTEND_URL:http://localhost:3000}

logging:
  level:
    root: INFO
    com.win.marketplace: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"